### ISSUE TITLE
公式（3）请教

### ISSUE THREAD

**Issue by Nikol-coder** [Lucius-lsr/NutePrune#1]
您好，请问论文中公式（3）中的 4 和 3 是怎么来的呀？
![1719312347511](https://github.com/Lucius-lsr/NutePrune/assets/64388410/cf4c67a3-cd55-4dfb-90f0-9e2ae6ffa824)

**Comment by digbangbang** [comment]
这个我也去搜过，不知道我说的对不对，4指的是QKVO，QKV就是attention里的块，O是多头attention的一个映射块（就是映射concat之后的注意力）。3的话指FFN层里，目前transformer通常使用一个gate，因此up块有两个，down块有1个，所以是3

**Comment by Lucius-lsr** [comment]
这个公式代表的是LLaMA结构（没有MQA），4是attention的 query key value output四个线性变换，他们参数量恰好是一样的。3是ffn的down gate up三个线性变换，参数量也恰好是一样的，所以这个公式长这样

**Comment by Nikol-coder** [comment]
好的，谢谢两位的解答，非常感谢！
