### ISSUE TITLE
时间消耗

### ISSUE THREAD

**Issue by Nikol-coder** [Lucius-lsr/NutePrune#2]
您好，想请问一下在这篇论文中，使用一张A100，这种迭代式剪纸+蒸馏的方法，它所需的时间消耗是怎么样的呢？想使用这篇论文的方法做模型压缩，想了解一下具体的时间成本

**Comment by Lucius-lsr** [comment]
A100在llama-7B上面训练，用20k C4数据训练7个epoch，大约12个小时

**Comment by Nikol-coder** [comment]
> A100在llama-7B上面训练，用20k C4数据训练7个epoch，大约12个小时

行，非常感谢！
